title: Singapore Customs
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/favicon.png

# Site colors
colors:
  primary-color: '#022c80'
  secondary-color: '#606060'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#022c80'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#606060'
    - title: media-color-five
      color: '#305072'

resources_name: news-and-media

collections:
  about-us:
    output: true
  individuals:
    output: true
  businesses:
    output: true
  news-and-media:
    output: true
  eservices:
    output: true

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test

